
import { StyleSheet } from 'react-native';
import { Constants, Images, Colors } from "@themes";
export default StyleSheet.create({
    container: { flex: 1, backgroundColor: Colors.bg },
    header: { height: 64 },
    content: { flex: 1, padding:10},
    profileView: {marginTop:10, flexDirection: 'row', alignItems: 'center',alignSelf:'center' },
    emptyImg: { height: 120, width: 120, marginLeft: 0, borderRadius: 60 },
    profilePic: { height: 120, width: 120, marginLeft: 0, borderRadius: 60 },
    dataView: { flex: 0.1, flexDirection: 'row', margin: 10 },
    phoneView: { flex: 0.5, backgroundColor: "#f3f3f3", flexDirection: 'row', alignItems: 'center', },
    emailView: { flex: 0.5, backgroundColor: Colors.theme, flexDirection: 'row', alignItems: 'center', },
    iconsView: { flex: 0.2, alignItems: 'flex-end', },
    inputView: { flex: 0.8 },
    listView: { flex: 0.7 },
    menuIcon: { height: 35, width: 35, tintColor: Colors.black },
    nameInput: {
        margin: 0,
        padding: 0,
        fontSize: 18,
        marginLeft: 15,
        fontWeight: 'bold'
    },
    icon: { height: 35, width: 35, tintColor: Colors.black },
    cartIcon: { height: 25, width: 25, tintColor: Colors.black },
    middleView: { flex: 0.8, justifyContent: 'center', alignItems: 'center', },
    textInputFlexView: {
        //backgroundColor: '#ffffff',
        shadowOpacity: 0,
        shadowOffset: { width: 0, height: 0 },
        shadowColor: "grey",
        elevation: 0,
        marginTop: 0,
        borderRadius: 0,
        flexDirection:"row",
        borderBottomWidth : 1.5,
        borderBottomColor:"#e2e2e2",
        paddingHorizontal: 10,
        paddingLeft: 20,
    },
    rightIconView: { flex: 0.35, flexDirection: 'row', alignItems: 'center', justifyContent: "flex-end" },
    leftIconView: { flex: 0.35, justifyContent: 'center', },
    passwordInputView: {
        //backgroundColor: '#ffffff',
        shadowOpacity: 0,
        shadowOffset: { width: 0, height: 0 },
        shadowColor: "grey",
        elevation: 0,
        marginTop: 0,
        borderRadius: 0,
        borderBottomWidth : 1.5,
        borderBottomColor:"#e2e2e2",
        justifyContent: 'center',
        paddingHorizontal: 10,
        paddingLeft: 20,
    },
    input: {
        margin: 0,
        padding: 0,
        fontSize: 16,
        color:'black',
        // fontWeight: 'bold',
        marginHorizontal: 0,
        flex:1
    },
    button: { marginTop: 20,backgroundColor:"#fe5c45",borderRadius:25 },
    inputtitle: { marginVertical: 15, fontSize: 16, fontWeight: "bold" },
    icon: { height: 20, width: 20, },
    row: {
        padding: 10,
        marginTop: 10,
        marginHorizontal: 10,

    },
    textInputView: {
        //backgroundColor: '#ffffff',
        shadowOpacity: 0,
        shadowOffset: { width: 0, height: 0 },
        shadowColor: "grey",
        elevation: 0,
        marginTop: 0,
        borderRadius: 0,
        borderBottomWidth : 1.5,
        borderBottomColor:"#e2e2e2",
        justifyContent: 'center',
        paddingHorizontal: 10,
        paddingLeft: 20,
    },
    textInputView1: {
        //backgroundColor: '#ffffff',
        shadowOpacity: 0,
        shadowOffset: { width: 0, height: 0 },
        shadowColor: "grey",
        elevation: 0,
        marginTop: 15,
        borderRadius: 0,
        borderBottomWidth : 1.5,
        borderBottomColor:"#e2e2e2",
        justifyContent: 'center',
        paddingHorizontal: 10,
        paddingLeft: 20,
    },
    rowMainContent: { flexDirection: "row" },
    pinIconView: { flex: 0.1 },
    pinIcon: { height: 25, width: 25, },
    rowContent: { flex: 0.9 },
    contentView: { flexDirection: 'row', justifyContent: "space-between", },
    title: { fontWeight: 'bold' },
    iconsContainer: { flexDirection: 'row', },
    iconView: {
        height: 28, width: 28, alignItems: 'center', justifyContent: 'center', borderRadius: 9,
        borderWidth: 1, borderColor: Colors.e4e4e4,
        backgroundColor: "white",
    },
    editIcon: { height: 10, width: 10, tintColor: Colors.theme },
    plusIcon: { height: 10, width: 10, tintColor: Colors.green },
    subText: { color: "grey", fontSize: 14, },
    address: { color: "dimgrey", fontSize: 12, marginTop: 5 },
    textInputContainer: {
        flexDirection: 'row',
      },
      textInput: {
        backgroundColor: '#FFFFFF',
        height: 44,
        borderRadius: 5,
        paddingVertical: 5,
        paddingHorizontal: 10,
        fontSize: 15,
        flex: 1,
      },
      poweredContainer: {
        justifyContent: 'flex-end',
        alignItems: 'center',
        borderBottomRightRadius: 5,
        borderBottomLeftRadius: 5,
        borderColor: '#c8c7cc',
        borderTopWidth: 0.5,
      },
      powered: {},
      listView: {},
      row: {
        backgroundColor: '#FFFFFF',
        padding: 13,
        height: 44,
        flexDirection: 'row',
      },
      separator: {
        height: 0.5,
        backgroundColor: '#c8c7cc',
      },
      description: {},
      loader: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        height: 20,
      },
});