const Images = {
  fullLogo: require("@Images/logo.png"),
  titleLogo: require("@Images/logo.png"),
  logo: require("@Images/logo.png"),
  bg: require("@Images/login-bg.png"),
  icons: {
    search: require("@Images/icons/search.png"),
    //downArrow: require("@Images/icons/down-arrow.png"),
    back: require("@Images/icons/back.png"),
    menu: require("@Images/icons/menu.png"),
    cart: require("@Images/icons/shopping-bag.png"),
    notification: require("@Images/icons/notification.png"),
    //grid: require("@Images/icons/grid.png"),
    //like: require("@Images/icons/like.png"),
    bag: require("@Images/icons/shopping-bag.png"),
    edit: require("@Images/icons/edit.png"),
    close: require("@Images/icons/close.png"),
    //user: require("@Images/icons/user.png"),
    pin: require("@Images/icons/location.png"),
    logout: require("@Images/icons/logout.png"),
    privacy: require("@Images/icons/security-shield.png"),

    privacy: require("@Images/icons/security-shield.png"),
    heart: require("@Images/icons/heart.png"),
    home: require("@Images/icons/home.png"),
    star: require("@Images/icons/star.png"),
    delete: require("@Images/icons/delete.png"),
    eye: require("@Images/icons/eye.png"),
    filter: require("@Images/icons/filter.png"),
    category: require("@Images/icons/category.png"),
    settings: require("@Images/icons/settings.png"),
    profile: require("@Images/icons/profile.png"),
    arrow: require("@Images/icons/arrow.png"),
    del: require("@Images/icons/del.png"),
    login: require("@Images/icons/login.png"),
    usdHome: require("@Images/icons/usd_home.png"),
    bell: require("@Images/icons/bell.png"),
    legalPolicy: require("@Images/icons/legal_policy.png"),
    customerService: require("@Images/icons/customer_service.png"),
    faq: require("@Images/icons/faq.png"),
    share: require("@Images/icons/share.png"),
    invite: require("@Images/icons/invite.png"),
    multiply: require("@Images/icons/multiply.png"),
    currentLocation: require("@Images/icons/current_location.png"),
    ex: require("@Images/icons/ex.png"),
  }

};

export default Images;
