import { StyleSheet } from 'react-native';
import { Colors } from "@themes";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.bg,
    },
    header: { height: 50 },
    content: { flex: 1,padding:15 },
    input: {
        margin: 0,
        padding: 0,
        fontSize: 16,
        color:'black',
        // fontWeight: 'bold',
        marginHorizontal: 0,
        flex:1
    },
    row: {
        shadowOpacity: 0.5,
        flex:1,
        shadowOffset: { width: 1, height: 1 },
        shadowColor: "grey",
        elevation: 0,
        backgroundColor: "white",
        padding: 15,
        marginBottom: 0,
        marginTop:0,
        marginHorizontal: 0,
        borderRadius: 5,

    },
    rowContent: { flexDirection: 'row', justifyContent: "space-between", },
    title: { fontWeight: 'bold' },
    time: { color: "grey", fontSize: 12, },
    pinIcon: { height: 20, width: 20,tintColor:"red" },
    button: { marginTop: 15,marginStart:25,marginEnd:25,marginBottom:15,backgroundColor:"#fe5c45",borderRadius:25 },
    desc: { color: "dimgrey", fontSize: 12, marginTop: 5 },
    icon: { height: 35, width: 35, tintColor: Colors.black },
    textInputFlexView: {
        //backgroundColor: '#ffffff',
        shadowOpacity: 0,
        shadowOffset: { width: 0, height: 0 },
        shadowColor: "grey",
        elevation: 0,
        marginTop: 10,
        height:50,
        borderRadius: 5,
        flexDirection:"row",
        borderWidth : 1,
        borderColor:"#e2e2e2",
        paddingHorizontal: 0,
        paddingLeft: 10,
    },
    textInputView: {
        //backgroundColor: '#ffffff',
        shadowOpacity: 0,
        shadowOffset: { width: 0, height: 0 },
        shadowColor: "grey",
        elevation: 0,
        marginTop: 10,
        height:50,
        width:'100%',
        borderRadius: 5,
        flexDirection:"row",
        borderWidth : 1,
        borderColor:"#e2e2e2",
        paddingHorizontal: 0,
        paddingLeft: 10,
    },
    textInputView1: {
        //backgroundColor: '#ffffff',
        shadowOpacity: 0,
        shadowOffset: { width: 0, height: 0 },
        shadowColor: "grey",
        elevation: 0,
        marginTop: 10,
        height:50,
        borderRadius: 5,
        flexDirection:"row",
        borderWidth : 1,
        borderColor:"#e2e2e2",
        paddingHorizontal: 0,
        paddingLeft: 10,
    },
    inputtitle: { marginVertical: 0,marginTop:10, fontSize: 16, fontWeight: "bold" },
});